name: Master commit CI

on:
  push:
    branches:
    - master

jobs:
  build:
    if: github.repository == 'ddialliance/ddimodel'
    runs-on: windows-latest

    steps:
    - name: Get short SHA
      run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Install cogs dotnet tool
      run: dotnet tool install --global --add-source https://ci.appveyor.com/nuget/cogs/ cogs

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install python dependencies
      run: pip install -r build/requirements.txt


    - name: Install other dependencies
      run: .\build\install-dependencies.ps1
      shell: pwsh

    - name: Run build-windows.bat
      run: .\build\build-windows.bat
      shell: cmd

    - name: Copy and rename outputs
      shell: pwsh
      run: |
        mkdir ddi-lifecycle
        xcopy ddi-lifecycle-all-outputs\xsd ddi-lifecycle\xsd /E /I
        xcopy ddi-lifecycle-all-outputs\json ddi-lifecycle\json /E /I
        xcopy ddi-lifecycle-all-outputs\owl ddi-lifecycle\rdf /E /I
        xcopy ddi-lifecycle-all-outputs\uml ddi-lifecycle\uml /E /I
        ren ddi-lifecycle ddi-lifecycle-${{env.SHORT_SHA}}
        ren ddi-lifecycle-all-outputs ddi-lifecycle-all-outputs-${{env.SHORT_SHA}}
        7z a -tzip "ddi-lifecycle-all-outputs-${{env.SHORT_SHA}}.zip" "ddi-lifecycle-all-outputs-${{ENV.SHORT_SHA}}\*"

    - name: Make all outputs artifact
      uses: actions/upload-artifact@v4
      with:
          name: ddi-lifecycle-all-outputs-${{env.SHORT_SHA}}
          path: ddi-lifecycle-all-outputs-${{env.SHORT_SHA}}.zip

    - name: Make package artifact
      uses: actions/upload-artifact@v4
      with:
        name: ddi-lifecycle-${{env.SHORT_SHA}}
        path: ddi-lifecycle-${{env.SHORT_SHA}}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Sync S3 dev bucket
      run: |
        aws s3 sync ddi-lifecycle-all-outputs-${{env.SHORT_SHA}}\sphinx\build\dirhtml s3://docs.ddialliance.org/DDI-Lifecycle/dev/model
        aws s3 cp ddi-lifecycle-${{env.SHORT_SHA}}\xsd\schema.xsd s3://docs.ddialliance.org/DDI-Lifecycle/dev/output/schema.xsd
        aws s3 cp ddi-lifecycle-${{env.SHORT_SHA}}\uml\ddi4.xmi s3://docs.ddialliance.org/DDI-Lifecycle/dev/output/ddi4.xmi
        aws s3 cp ddi-lifecycle-${{env.SHORT_SHA}}\json\jsonSchema.json s3://docs.ddialliance.org/DDI-Lifecycle/dev/output/jsonSchema.json
        aws s3 cp ddi-lifecycle-all-outputs-${{env.SHORT_SHA}}\dctap\dctap.csv s3://docs.ddialliance.org/DDI-Lifecycle/dev/output/dctap.csv
        aws s3 cp ddi-lifecycle-${{env.SHORT_SHA}}\rdf\ddi4.owl.ttl s3://docs.ddialliance.org/DDI-Lifecycle/dev/output/ddi4.owl.ttl 
        aws s3 cp ddi-lifecycle-${{env.SHORT_SHA}}\rdf\ddi4.shex s3://docs.ddialliance.org/DDI-Lifecycle/dev/output/ddi4.shex       
        aws s3 cp ddi-lifecycle-${{env.SHORT_SHA}}\rdf\ddi4.shacl s3://docs.ddialliance.org/DDI-Lifecycle/dev/output/ddi4.shacl

